//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotakTraceAPI.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KotakTraceEntities : DbContext
    {
        public KotakTraceEntities()
            : base("name=KotakTraceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Assigned_MenuMaster> tbl_Assigned_MenuMaster { get; set; }
        public virtual DbSet<tbl_Assigned_RoleMaster> tbl_Assigned_RoleMaster { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Login_History> tbl_Login_History { get; set; }
        public virtual DbSet<tbl_MenuMaster> tbl_MenuMaster { get; set; }
        public virtual DbSet<tbl_RoleMaster> tbl_RoleMaster { get; set; }
    
        public virtual ObjectResult<SP_MenuBind_Result> SP_MenuBind(Nullable<int> emp_Id)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("Emp_Id", emp_Id) :
                new ObjectParameter("Emp_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MenuBind_Result>("SP_MenuBind", emp_IdParameter);
        }
    
        public virtual ObjectResult<SP_VerifyLogin_Result> SP_VerifyLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VerifyLogin_Result>("SP_VerifyLogin", usernameParameter, passwordParameter);
        }
    }
}
