//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotakTraceAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login_History
    {
        public int Id { get; set; }
        public string IP_Address { get; set; }
        public string System_Name { get; set; }
        public string Host_Name { get; set; }
        public Nullable<System.DateTime> Login_Date { get; set; }
        public int Emp_Id { get; set; }
    }
}
