//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotakTraceAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Assigned_RoleMaster
    {
        public int Id { get; set; }
        public int Emp_Id { get; set; }
        public int Role_Id { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public int Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
